### ISSUE TITLE
Ambiguous function call to 'computeLog' on macOS

### ISSUE THREAD

**Issue by marcelmaltry** [stoianmihail/CHT#2]
### System configuration
OS: macOS 11.4
Compiler: AppleClang 12.0.5.12050022

### Issue
The project does not compile under the given system configuration due to an ambiguous function call to `computeLog`. The function is defined for both `uint64_t` and `uint32_t` but called with a `size_t` in the initializer list. 
```
In file included from ../example.cc:6:
../include/cht/builder.h:23:23: error: call to 'computeLog' is ambiguous
        log_num_bins_(computeLog(num_bins_)),
                      ^~~~~~~~~~
../example.cc:22:25: note: in instantiation of member function 'cht::Builder<unsigned int>::Builder' requested here
  cht::Builder<KeyType> chtb(min, max, numBins, maxError, false, useCache);
                        ^
../example.cc:38:3: note: in instantiation of function template specialization 'CompactHistTreeExample<unsigned int>' requested here
  CompactHistTreeExample<uint32_t>();
  ^
../include/cht/builder.h:94:19: note: candidate function
  static unsigned computeLog(uint32_t n, bool round = false) {
                  ^
../include/cht/builder.h:99:19: note: candidate function
  static unsigned computeLog(uint64_t n, bool round = false) {
                  ^
```

### Steps to reproduce
```
mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```
### How to resolve?
There are a number of options to resolve the issue:
* cast the `num_bins_` in the initializer list to either `uint64_t` or `uint32_t`
* remove `computeLog(uint32_t n, bool round)`
* change `num_bins_` to `uint64_t` or `uint32_t`

**Comment by andreaskipf** [comment]
Thanks Marcel! The issue should be fixed now.
